### ISSUE TITLE
Bulk transfer through  the hub

### ISSUE THREAD

**Issue by Kisdlsskxnxkxn** [rtek1000/STM32F4HUB_modified#1]
Hello, when the USB flash drive or cdc device is identified, how does the stm32f407 BULK transfer data to the device through the hub

**Comment by rtek1000** [comment]
Hello, unfortunately the ST does not support USB Host HUB for almost all STM32s (if not all), it's been over a decade since these MCUs were released, and until now there isn't a library available, probably for some reason. There is an explanation related to this problem, which may force the user to look for another alternative, such as using the NXP MCU.

Please, see this note: https://github.com/rtek1000/Datalogger_2039#stm32-internal-hardware-usb

Note: I'm going to leave this issue closed, as I can't help much more with this request, but if necessary, please feel free to reopen it, thanks.
